# Generated by Django 2.1.5 on 2019-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('actualsalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('designation', models.CharField(max_length=30)),
                ('shift', models.CharField(max_length=30)),
                ('loans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netsalary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
