# Generated by Django 2.1.7 on 2019-03-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app28', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='useername',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='useername',
            new_name='username',
        ),
    ]
