# Generated by Django 2.1.7 on 2019-03-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=30)),
                ('contactno', models.IntegerField()),
                ('area', models.TextField()),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
