# Generated by Django 2.1.7 on 2019-02-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app21', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salalry',
            new_name='salary',
        ),
    ]
