# Generated by Django 2.1.7 on 2019-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contactno', models.IntegerField()),
                ('email', models.CharField(default=False, max_length=10)),
            ],
        ),
    ]
