# Generated by Django 2.1.7 on 2019-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('Idno', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ContactNo', models.IntegerField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Pincode', models.IntegerField(max_length=30)),
            ],
        ),
    ]
