# Generated by Django 2.1.7 on 2019-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='ContactNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='Pincode',
            field=models.IntegerField(),
        ),
    ]
