# Generated by Django 2.1.7 on 2019-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190323_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('ContactNo', models.IntegerField()),
                ('EmailId', models.EmailField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('Feedback', models.TextField()),
            ],
        ),
    ]
