# Generated by Django 2.1.7 on 2019-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(upload_to='media/staff'),
        ),
    ]
